import type { MediaItem } from "@/stores/app-store";

// ─── Trending Anime ─────────────────────────────────────────────────────────
export const TRENDING_ANIME: MediaItem[] = [
  {
    id: "anime-1",
    media_type: "anime",
    title: "Frieren: Beyond Journey's End",
    slug: "mal-52991",
    year: 2023,
    rating: 92,
    match: 97,
    genres: ["Fantasy", "Adventure", "Drama"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/dqZENchTd7lp5zht7BdlqFOjNMV.jpg",
    author: "Madhouse",
    description: "After the party of heroes defeated the Demon King, the aftermath of their quest brings a new journey of self-discovery for the elven mage Frieren.",
  },
  {
    id: "anime-2",
    media_type: "anime",
    title: "Solo Leveling",
    slug: "mal-52299",
    year: 2024,
    rating: 86,
    match: 91,
    genres: ["Action", "Fantasy", "Adventure"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
    author: "A-1 Pictures",
    description: "In a world where hunters battle deadly monsters, Sung Jinwoo starts as the weakest but gains a mysterious power that lets him level up without limits.",
  },
  {
    id: "anime-3",
    media_type: "anime",
    title: "Attack on Titan",
    slug: "mal-16498",
    year: 2013,
    rating: 90,
    match: 95,
    genres: ["Action", "Drama", "Dark Fantasy"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    author: "WIT Studio / MAPPA",
    description: "Humanity's last remnants live behind enormous walls to protect themselves from giant humanoid creatures known as Titans.",
  },
  {
    id: "anime-4",
    media_type: "anime",
    title: "Jujutsu Kaisen",
    slug: "mal-40748",
    year: 2020,
    rating: 87,
    match: 88,
    genres: ["Action", "Supernatural", "School"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/hFWP5HkbVEe40hrXfsKBGbEMem.jpg",
    author: "MAPPA",
    description: "A boy swallows a cursed talisman and enrolls in a school of sorcerers to save the world.",
  },
  {
    id: "anime-5",
    media_type: "anime",
    title: "Vinland Saga",
    slug: "mal-37521",
    year: 2019,
    rating: 88,
    match: 93,
    genres: ["Action", "Historical", "Drama"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/7nOOdrmmgrELyBlGT3VhODh5GM6.jpg",
    author: "WIT Studio",
    description: "A young Viking warrior seeks revenge against the man who killed his father, while questioning the cycle of violence.",
  },
  {
    id: "anime-6",
    media_type: "anime",
    title: "Demon Slayer",
    slug: "mal-38000",
    year: 2019,
    rating: 87,
    match: 86,
    genres: ["Action", "Fantasy", "Supernatural"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/wrCVHdkBlBWdJUZPvnJWcBRuhSY.jpg",
    author: "ufotable",
    description: "A kind-hearted boy becomes a demon slayer after his family is slaughtered and his sister turned into a demon.",
  },
  {
    id: "anime-7",
    media_type: "anime",
    title: "Spy x Family",
    slug: "mal-50265",
    year: 2022,
    rating: 84,
    match: 82,
    genres: ["Comedy", "Action", "Slice of Life"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/3r4LYFuXng4MJOKRUE35kKxIhkP.jpg",
    author: "WIT Studio",
    description: "A spy, an assassin, and a telepath form a fake family, each hiding their secrets from one another.",
  },
  {
    id: "anime-8",
    media_type: "anime",
    title: "Cyberpunk: Edgerunners",
    slug: "mal-42310",
    year: 2022,
    rating: 86,
    match: 90,
    genres: ["Sci-Fi", "Action", "Cyberpunk"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/7jSWMU4hL1ePBksy49mY5MOMi5P.jpg",
    author: "Studio Trigger",
    description: "A street kid in Night City tries to survive by becoming an edgerunner — a mercenary outlaw with cybernetic enhancements.",
  },
];

// ─── Popular Games ──────────────────────────────────────────────────────────
export const POPULAR_GAMES: MediaItem[] = [
  {
    id: "game-1",
    media_type: "game",
    title: "Elden Ring",
    slug: "igdb-119133",
    year: 2022,
    rating: 96,
    match: 98,
    genres: ["Action RPG", "Open World", "Dark Fantasy"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/sXybjMJLfGPOsBMBRH5Dv3gfKR.jpg",
    author: "FromSoftware",
    description: "An action RPG set in the Lands Between, a vast realm ruled by demigods who wield the shards of the Elden Ring.",
  },
  {
    id: "game-2",
    media_type: "game",
    title: "Baldur's Gate 3",
    slug: "igdb-119171",
    year: 2023,
    rating: 96,
    match: 95,
    genres: ["RPG", "Turn-Based", "Fantasy"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/bm33jEB8jlblRxAiIiXnlh4brHo.jpg",
    author: "Larian Studios",
    description: "Gather your party and return to the Forgotten Realms in an epic tale of fellowship and betrayal.",
  },
  {
    id: "game-3",
    media_type: "game",
    title: "The Legend of Zelda: TotK",
    slug: "igdb-119388",
    year: 2023,
    rating: 95,
    match: 93,
    genres: ["Adventure", "Open World", "Action"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/t8iJOmHMwCiKsFkJeRmjOhkFGAD.jpg",
    author: "Nintendo",
    description: "An epic adventure across the land and skies of Hyrule awaits in the sequel to Breath of the Wild.",
  },
  {
    id: "game-4",
    media_type: "game",
    title: "God of War Ragnarök",
    slug: "igdb-119277",
    year: 2022,
    rating: 94,
    match: 90,
    genres: ["Action", "Adventure", "Mythology"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/b6myFnMhNGPjfSukyVE3n3iVLyD.jpg",
    author: "Santa Monica Studio",
    description: "Kratos and Atreus journey across the Nine Realms as Norse mythology's Ragnarök approaches.",
  },
  {
    id: "game-5",
    media_type: "game",
    title: "Hades",
    slug: "igdb-106987",
    year: 2020,
    rating: 93,
    match: 94,
    genres: ["Roguelike", "Action", "Mythology"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/gwt3JMCOVoQNPkKuC5sHnXGhpvP.jpg",
    author: "Supergiant Games",
    description: "Defy the god of the dead as you hack and slash your way out of the Underworld of Greek myth.",
  },
  {
    id: "game-6",
    media_type: "game",
    title: "Hollow Knight",
    slug: "igdb-26758",
    year: 2017,
    rating: 90,
    match: 89,
    genres: ["Metroidvania", "Indie", "Action"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/oXLqfk8RhRpR2HnhviGPGxGGIgD.jpg",
    author: "Team Cherry",
    description: "Forge your own path through the insect kingdom of Hallownest in this beautifully crafted Metroidvania.",
  },
  {
    id: "game-7",
    media_type: "game",
    title: "Persona 5 Royal",
    slug: "igdb-115278",
    year: 2020,
    rating: 95,
    match: 96,
    genres: ["JRPG", "Turn-Based", "Social Sim"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/pNOccytgkGYPpBMFTlKOPHhECpH.jpg",
    author: "Atlus",
    description: "Don the mask of Joker and join the Phantom Thieves as you steal the hearts of corrupt adults.",
  },
  {
    id: "game-8",
    media_type: "game",
    title: "Celeste",
    slug: "igdb-25076",
    year: 2018,
    rating: 92,
    match: 85,
    genres: ["Platformer", "Indie", "Precision"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/t0Dz21yF8g7Cj1KhJQYnZeDJR5q.jpg",
    author: "Maddy Makes Games",
    description: "Help Madeline survive her inner demons as she makes her way to the summit of Celeste Mountain.",
  },
];

// ─── Recommended Books ──────────────────────────────────────────────────────
export const RECOMMENDED_BOOKS: MediaItem[] = [
  {
    id: "book-1",
    media_type: "book",
    title: "Dune",
    slug: "book-dune001",
    year: 1965,
    rating: 90,
    match: 95,
    genres: ["Sci-Fi", "Epic", "Political"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    author: "Frank Herbert",
    description: "Set in the distant future amidst a feudal interstellar society, Dune tells the story of young Paul Atreides.",
  },
  {
    id: "book-2",
    media_type: "book",
    title: "The Name of the Wind",
    slug: "book-notw001",
    year: 2007,
    rating: 88,
    match: 93,
    genres: ["Fantasy", "Adventure", "Coming of Age"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/rR80sKM62bQLx1YihxgGTGBJdN7.jpg",
    author: "Patrick Rothfuss",
    description: "The tale of Kvothe — musician, warrior, hero, legend — told in his own words.",
  },
  {
    id: "book-3",
    media_type: "book",
    title: "Project Hail Mary",
    slug: "book-phm001",
    year: 2021,
    rating: 92,
    match: 97,
    genres: ["Sci-Fi", "Adventure", "Humor"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/cBhM0JlSjK2rGv4P8A3F0pQjPSm.jpg",
    author: "Andy Weir",
    description: "A lone astronaut wakes up on a spaceship with no memory and must save humanity from extinction.",
  },
  {
    id: "book-4",
    media_type: "book",
    title: "The Way of Kings",
    slug: "book-wok001",
    year: 2010,
    rating: 91,
    match: 94,
    genres: ["Epic Fantasy", "Military", "Magic"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/uAqkNHsVJDYBvjNPTsuGdsxkStI.jpg",
    author: "Brandon Sanderson",
    description: "The first book of The Stormlight Archive, an epic fantasy series set in the world of Roshar.",
  },
  {
    id: "book-5",
    media_type: "book",
    title: "Neuromancer",
    slug: "book-neuro001",
    year: 1984,
    rating: 82,
    match: 88,
    genres: ["Cyberpunk", "Sci-Fi", "Noir"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/k3LsEXfkCb2Q1woxXOVDO1sINer.jpg",
    author: "William Gibson",
    description: "A washed-up hacker is hired for one last job in this genre-defining cyberpunk novel.",
  },
  {
    id: "book-6",
    media_type: "book",
    title: "1984",
    slug: "book-1984",
    year: 1949,
    rating: 88,
    match: 82,
    genres: ["Dystopian", "Political Fiction", "Classic"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/pFqLvvLJFjERnjxShxnbtF6O2JD.jpg",
    author: "George Orwell",
    description: "A dystopian novel set in Airstrip One, a totalitarian society ruled by Big Brother.",
  },
  {
    id: "book-7",
    media_type: "book",
    title: "The Hobbit",
    slug: "book-hobbit001",
    year: 1937,
    rating: 87,
    match: 86,
    genres: ["Fantasy", "Adventure", "Classic"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/lKiVbSMjCSn4smv1j41P3mPHqRX.jpg",
    author: "J.R.R. Tolkien",
    description: "Bilbo Baggins is swept into an epic quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug.",
  },
  {
    id: "book-8",
    media_type: "book",
    title: "Fourth Wing",
    slug: "book-fw001",
    year: 2023,
    rating: 83,
    match: 84,
    genres: ["Fantasy", "Romance", "Military"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/bWQnFb3JIhQj0e5m2gLQpJxNuPo.jpg",
    author: "Rebecca Yarros",
    description: "Twenty-year-old Violet Sorrengail was supposed to live a quiet life, but is forced into dragon rider training.",
  },
];

// ─── Binge-Worthy TV ────────────────────────────────────────────────────────
export const BINGEWORTHY_TV: MediaItem[] = [
  {
    id: "tv-1",
    media_type: "tv",
    title: "Breaking Bad",
    slug: "tmdb-1396",
    year: 2008,
    rating: 95,
    match: 96,
    genres: ["Drama", "Crime", "Thriller"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    author: "Vince Gilligan",
    description: "A high school chemistry teacher diagnosed with cancer begins manufacturing methamphetamine.",
  },
  {
    id: "tv-2",
    media_type: "tv",
    title: "Severance",
    slug: "tmdb-95396",
    year: 2022,
    rating: 88,
    match: 93,
    genres: ["Thriller", "Sci-Fi", "Mystery"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/lFf6LLrQjYFKnFRFmB5RhHiDcOu.jpg",
    author: "Dan Erickson",
    description: "Mark leads a team of office workers whose memories have been surgically divided between work and personal lives.",
  },
  {
    id: "tv-3",
    media_type: "tv",
    title: "The Bear",
    slug: "tmdb-136315",
    year: 2022,
    rating: 87,
    match: 85,
    genres: ["Drama", "Comedy", "Food"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/sJhFtY3HKDM0VPZxRBIhKHeDqAL.jpg",
    author: "Christopher Storer",
    description: "A young chef from fine dining returns to Chicago to run his family's sandwich shop.",
  },
  {
    id: "tv-4",
    media_type: "tv",
    title: "Succession",
    slug: "tmdb-76331",
    year: 2018,
    rating: 89,
    match: 88,
    genres: ["Drama", "Comedy", "Family"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/e2NH9vsFEnJHATqLgOTofvG5Bq4.jpg",
    author: "Jesse Armstrong",
    description: "The Roy family controls one of the biggest media conglomerates, but succession is a bloody affair.",
  },
  {
    id: "tv-5",
    media_type: "tv",
    title: "Shogun",
    slug: "tmdb-126308",
    year: 2024,
    rating: 90,
    match: 92,
    genres: ["Drama", "Historical", "War"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
    author: "Rachel Kondo & Justin Marks",
    description: "In 1600 Japan, a shipwrecked English navigator becomes embroiled in a power struggle between feudal lords.",
  },
  {
    id: "tv-6",
    media_type: "tv",
    title: "Dark",
    slug: "tmdb-72680",
    year: 2017,
    rating: 88,
    match: 91,
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    author: "Baran bo Odar",
    description: "A missing child ignites a mind-bending mystery spanning four generations in a German town.",
  },
  {
    id: "tv-7",
    media_type: "tv",
    title: "Arcane",
    slug: "tmdb-94605",
    year: 2021,
    rating: 90,
    match: 94,
    genres: ["Animation", "Action", "Sci-Fi"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    author: "Fortiche / Riot Games",
    description: "Amid the turmoil between the cities of Piltover and Zaun, two sisters fight on rival sides of a war.",
  },
  {
    id: "tv-8",
    media_type: "tv",
    title: "The Last of Us",
    slug: "tmdb-100088",
    year: 2023,
    rating: 88,
    match: 90,
    genres: ["Drama", "Post-Apocalyptic", "Adventure"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    author: "Craig Mazin & Neil Druckmann",
    description: "Joel and Ellie cross a post-apocalyptic United States in a brutal journey of survival.",
  },
];

// ─── Classic Films ──────────────────────────────────────────────────────────
export const CLASSIC_FILMS: MediaItem[] = [
  {
    id: "film-1",
    media_type: "film",
    title: "Interstellar",
    slug: "tmdb-157336",
    year: 2014,
    rating: 86,
    match: 94,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    author: "Christopher Nolan",
    description: "When Earth becomes uninhabitable, a team of explorers travel through a wormhole to find a new home for humanity.",
  },
  {
    id: "film-2",
    media_type: "film",
    title: "Spirited Away",
    slug: "tmdb-129",
    year: 2001,
    rating: 87,
    match: 96,
    genres: ["Animation", "Fantasy", "Adventure"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    author: "Hayao Miyazaki",
    description: "A young girl becomes trapped in a mysterious spirit world and must find a way to free herself and her parents.",
  },
  {
    id: "film-3",
    media_type: "film",
    title: "Blade Runner 2049",
    slug: "tmdb-335984",
    year: 2017,
    rating: 80,
    match: 92,
    genres: ["Sci-Fi", "Drama", "Noir"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    author: "Denis Villeneuve",
    description: "A young blade runner discovers a long-buried secret that has the potential to plunge what's left of society into chaos.",
  },
  {
    id: "film-4",
    media_type: "film",
    title: "Parasite",
    slug: "tmdb-496243",
    year: 2019,
    rating: 86,
    match: 89,
    genres: ["Thriller", "Drama", "Dark Comedy"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    author: "Bong Joon-ho",
    description: "Greed and class discrimination threaten the symbiotic relationship between a wealthy family and a destitute one.",
  },
  {
    id: "film-5",
    media_type: "film",
    title: "The Dark Knight",
    slug: "tmdb-155",
    year: 2008,
    rating: 90,
    match: 91,
    genres: ["Action", "Crime", "Superhero"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/qJ2tW6WMUDux911BTUgMe1nFK1.jpg",
    author: "Christopher Nolan",
    description: "Batman faces The Joker, a criminal mastermind who plunges Gotham City into anarchy.",
  },
  {
    id: "film-6",
    media_type: "film",
    title: "Your Name",
    slug: "tmdb-372058",
    year: 2016,
    rating: 86,
    match: 93,
    genres: ["Animation", "Romance", "Fantasy"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/q719jXXEhI1THrNY5eFMn2jm8ZA.jpg",
    author: "Makoto Shinkai",
    description: "Two teenagers discover they are magically and intermittently swapping bodies, then set out to meet.",
  },
  {
    id: "film-7",
    media_type: "film",
    title: "Whiplash",
    slug: "tmdb-244786",
    year: 2014,
    rating: 85,
    match: 87,
    genres: ["Drama", "Music", "Thriller"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    author: "Damien Chazelle",
    description: "A promising young drummer enrolls at a cut-throat music conservatory with a terrifying instructor.",
  },
  {
    id: "film-8",
    media_type: "film",
    title: "Everything Everywhere All at Once",
    slug: "tmdb-545611",
    year: 2022,
    rating: 81,
    match: 90,
    genres: ["Sci-Fi", "Comedy", "Adventure"],
    cover_image_url: "https://image.tmdb.org/t/p/w300/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    author: "Daniel Kwan & Daniel Scheinert",
    description: "An aging Chinese immigrant gets swept up in an insane adventure where she alone can save the multiverse.",
  },
];

// ─── All mock data combined ─────────────────────────────────────────────────
export const ALL_MOCK_MEDIA: MediaItem[] = [
  ...TRENDING_ANIME,
  ...POPULAR_GAMES,
  ...RECOMMENDED_BOOKS,
  ...BINGEWORTHY_TV,
  ...CLASSIC_FILMS,
];
